sourceSets {
    main {
        java {
            srcDirs = ['src/main/java']
        }
        resources {
            srcDirs = ['src/main/resources']
        }
    }
    test {
        java {
            srcDirs = ['src/test/java']
        }
        resources {
            srcDirs = ['src/test/resources']
        }
    }
}

dependencies {
    implementation project(':intermine-webapp')
    testImplementation project(':intermine-objectstore')
    testImplementation project(':intermine-resources')
    testImplementation project(path: ':intermine-testresources', configuration: 'testArtifacts')
}
