sourceSets {
    main {
        java {
            srcDirs = ['src/main/java']
        }
        resources {
            srcDirs = ['src/main/resources']
        }
    }
    test {
        java {
            srcDirs = ['src/test/java']
        }
        resources {
            srcDirs = ['src/test/resources']
        }
    }
}

tasks.test.dependsOn(':intermine-testresources:buildDB')

configurations {
    provided
    compile.extendsFrom provided
    testOutput
}

dependencies {
    implementation project(':intermine-pathquery')
    implementation project(':intermine-integrate')
    implementation group: 'xalan', name: 'xalan', version: '2.7.3' // version 1.3 not in maven
    implementation group: 'org.apache.solr', name: 'solr-solrj', version: '8.11.4'
    implementation group: 'org.apache.lucene', name: 'lucene-core', version: '3.0.2'
    implementation group: 'org.apache.lucene', name: 'lucene-snowball', version: '3.0.2'
    implementation group: 'org.apache.lucene', name: 'lucene-highlighter', version: '3.0.2'
    implementation group: 'org.apache.lucene', name: 'lucene-queries', version: '3.0.2'
    implementation group: 'org.json', name: 'json', version: '20231013'
    implementation group: "org.apache.jena", name: "apache-jena-libs", version: "4.2.0"
    testImplementation project(path: ':intermine-testresources', configuration: 'testArtifacts')
    testImplementation group: 'xmlunit', name: 'xmlunit', version: '1.0'
    testImplementation project(path: ':intermine-objectstore', configuration: 'testOutput')
    testImplementation project(':intermine-resources')
}

tasks.named('jar', Jar) {
    from({
        configurations.provided.collect { file ->
            file.isDirectory() ? file : zipTree(file)
        }
    })

    from({
        configurations.runtimeClasspath.collect { file ->
            file.isDirectory() ? file : zipTree(file)
        }
    })
}

artifacts {
    testOutput sourceSets.test.output.files
}
