apply plugin: 'antlr'

sourceSets {
    main {
        java {
            srcDirs = ['src/main/java', 'build/generated-src/antlr/main']
        }
        resources {
            srcDirs = ['src/main/resources']
        }
        antlr {
            srcDirs = ['src/main/antlr']
        }
    }
    test {
        java {
            srcDirs = ['src/test/java']
        }
        resources {
            srcDirs = ['src/test/resources']
        }
    }
}

tasks.test.dependsOn(':intermine-testresources:buildDB')

dependencies {
    implementation project(':intermine-model')
    implementation 'org.apache.commons:commons-lang3:3.19.0'
    antlr 'org.antlr:antlr:2.7.6-caching'
    runtimeOnly group: 'stax', name: 'stax', version: '1.2.0'
}
