sourceSets {
    main {
        java {
            srcDirs = ['src/main/java']
        }
        resources {
            srcDirs = ['src/main/resources']
        }
    }

    test {
        java {
            srcDirs = ['src/test/java']
        }
        resources {
            srcDirs = ['src/test/resources']
        }
    }
}

tasks.test.dependsOn(':intermine-testresources:buildDB')

dependencies {
    implementation group: 'org.apache.commons', name: 'commons-lang3', version: '3.19.0'
    implementation group: 'org.apache.commons', name: 'commons-collections4', version: '4.5.0'
    implementation group: 'cglib', name: 'cglib', version: '3.1'
    implementation group: 'commons-io', name: 'commons-io', version: '2.20.0'
    implementation group: 'org.skyscreamer', name: 'jsonassert', version: '1.5.3'
    implementation group: 'org.ow2.asm', name: 'asm', version: '4.2'
}
