apply plugin: 'antlr'

sourceSets {
    main {
        java {
            srcDirs = ['src/main/java', 'build/generated-src/antlr/main']
        }
        antlr {
            srcDirs = ['src/main/antlr']
        }
    }
}

configurations {
    provided
    compile.extendsFrom provided
    testOutput
}

tasks.test.dependsOn(':intermine-testresources:buildDB')

dependencies {
    implementation project(':intermine-model')
    implementation 'org.postgresql:postgresql:42.7.8'
    implementation 'commons-io:commons-io:2.20.0'
    implementation 'commons-beanutils:commons-beanutils:1.11.0'
    implementation 'org.apache.torque:torque-runtime:5.1'
    implementation group: 'com.zaxxer', name: 'HikariCP', version: '3.2.0', transitive: false // conflict with log4j library this JAR needs
    //implementation 'org.slf4j:slf4j-jdk14:1.7.10' // hikari needs this

    implementation group: 'net.iharder', name: 'base64', version: '2.3.8' //not clear wich version is currently used
    implementation group: 'au.com.bytecode', name: 'opencsv', version: '2.4' //version 2.3 not available in maven
    implementation group: 'org.ow2.asm', name: 'asm', version: '4.2'
    implementation group: 'mockobjects', name: 'mockobjects-core', version: '0.09'
    implementation group: 'mockobjects', name: 'mockobjects-jdk1.3', version: '0.09'
    provided fileTree(dir: 'libs', include: '*.jar') // eventually replace torque
    testImplementation project(path: ':intermine-testresources', configuration: 'testArtifacts')
    antlr 'org.antlr:antlr:2.7.6-caching'
}

tasks.named('jar', Jar) {
    from({
        configurations.provided.collect { file ->
            file.isDirectory() ? file : zipTree(file)
        }
    })

    from({
        configurations.runtimeClasspath.collect { file ->
            file.isDirectory() ? file : zipTree(file)
        }
    })
}

artifacts {
    testOutput sourceSets.test.output.files
}
